export { GameAbout } from './game-about'
export { default as GameDescription } from './game-description'
export { GameExternalLinks } from './game-external-links'
export { GameHeader } from './game-header'
export { GameRatings } from './game-ratings'
export { default as GameScreenshots } from './game-screenshots'
export { GameSidebar } from './game-sidebar'
export { GameSpecifications } from './game-specifications'
export { SpecRow } from './spec-row'
